trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build Project'

  - script: npm test
    displayName: 'Run Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
